name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - smalltalk: Pharo64-12
            spec: .smalltalk.ston
            coverage: false
          - smalltalk: Pharo64-13
            spec: .smalltalk.coverage.ston
            coverage: true
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v4
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.spec }}
        shell: bash
        timeout-minutes: 15
      - name: Coveralls
        if: ${{ matrix.coverage }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/lcov.info
